owner: metatext
repo: status
sites:
  - name: Metatext (metatext.ai)
    method: GET
    url: https://metatext.ai
    icon: https://metatext.io/favicon.png
    expectedStatusCodes:
     - 200
     
  - name: Metatext App (app.metatext.ai)
    method: GET
    url: https://app.metatext.ai
    icon: https://metatext.io/favicon.png
    expectedStatusCodes:
     - 200

  - name: Training API (api.metatext.ai/v1/training)
    method: POST
    url: $TRAINING_ENDPOINT
    icon: https://aws.amazon.com/favicon.ico
    headers:
     - "x-api-key: $API_KEY"
     - "Content-Type: application/json"
    body: '{ "text": "hello world" }'
    expectedStatusCodes:
     - 200
    
  - name: Inference API (api.metatext.ai/v1/models)
    method: POST
    url: $INFERENCE_API
    icon: https://aws.amazon.com/favicon.ico
    headers:
     - "x-api-key: $API_KEY"
     - "Content-Type: application/json"
    body: '{ "text": "hello world" }'
    expectedStatusCodes:
     - 200
     
  - name: PIPELINE API
    method: POST
    url: $PIPELINE_API
    icon: https://aws.amazon.com/favicon.ico
    expectedStatusCodes:
     - 200

workflowSchedule:
  graphs: "* * * * *"
  responseTime: "* * * * *"
  staticSite: "* * * * *"
  summary: "* * * * *"
  updateTemplate: "* * * * *"
  updates: "* * * * *"
  uptime: "* * * * *"
  
assignees:
  - rafaelsandroni
status-website:
  cname: status.metatext.io
  logoUrl: https://metatext.io/favicon.png
  favicon: https://metatext.io/favicon.png
  icon: https://metatext.io/favicon.png
  name: AI services status - Metatext
  introTitle: Metatext Status Dashboard
  introMessage: This page provides status information on the services that are part of Metatext Cloud Platform. Check back here to view the current status of the services listed below. If you are experiencing an issue not listed here, please open an issue on Support page. 
  navbar:
    - title: Support 
      href: https://github.com/metatext/status/issues
