# Change these first
owner: rafaelsandroni # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Inference API
    url: https://www.google.com
  - name: Training API (AutoNLP.ai)
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  baseUrl: /status
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Metatext.io Status API
  introTitle: "**Status** of our AI services. Here you found our API's health, such as latency and incidents."
  introMessage: Metatext provide machine learning models in a game changing ease to use, with best accuracy and performance. 
  navbar:
    - title: Status
      href: /
    - title: Metatext
      href: https://metatext.io
    - title: AutoNLP.ai
      href: https://autonlp.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
