owner: metatext
repo: status
sites:
  - name: Metatext UI
    url: https://metatext.io
    icon: https://metatext.io/favicon.png
  - name: Inference API
    url: $INFERENCE_API/ping
    icon: https://aws.amazon.com/favicon.ico
  - name: Training API
    url: $INFERENCE_API/ping
    icon: https://aws.amazon.com/favicon.ico
assignees:
  - rafaelsandroni
status-website:
  cname: status.metatext.io
  logoUrl: https://metatext.io/favicon.png
  icon: https://metatext.io/favicon.png
  name: Metatext
  introTitle: Metatext Status Dashboard
  introMessage: This page provides status information on the services that are part of Metatext Cloud Platform. Check back here to view the current status of the services listed below. If you are experiencing an issue not listed here, please open an issue on Support page. 
  navbar:
    - title: Support 
      href: https://github.com/metatext/status/issues
