owner: metatext
repo: status
sites:
  - name: Metatext
    url: https://www.google.com
  - name: Inference API
    url: https://aws.amazon.com/
assignees:
  - rafaelsandroni
status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Metatext Status
  introTitle: "**Status** of our AI services. Here you found our API's health, such as latency and incidents."